<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Gayatris-MacBook-Air.local" failures="1" tests="6" name="Test" time="12.369" errors="0" timestamp="2025-08-11T13:19:52 IST">
  <testcase classname="com.ve3globaltest.tasks.DataDrivenLoginTest" name="verifyHomepageLoadsAfterValidLogin" time="0.894"/>
  <testcase classname="com.ve3globaltest.tasks.DataDrivenLoginTest" name="verifyHomepageLoadsAfterValidLogin" time="0.207"/>
  <testcase classname="com.ve3globaltest.tasks.DataDrivenLoginTest" name="verifyHomepageLoadsAfterValidLogin" time="5.171"/>
  <testcase classname="com.ve3globaltest.tasks.ProductCheckOutFlow" name="verifyProductFilterPriceLowToHigh" time="1.003"/>
  <testcase classname="com.ve3globaltest.tasks.ProductCheckOutFlow" name="validateCartFunctionality" time="0.451"/>
  <testcase classname="com.ve3globaltest.tasks.ProductCheckOutFlow" name="validateCheckoutFunctionality" time="0.511">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.ve3globaltest.tasks.ProductCheckOutFlow.validateCheckoutFunctionality(ProductCheckOutFlow.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validateCheckoutFunctionality -->
</testsuite> <!-- Test -->
